"""add price column to ticket_type

Revision ID: 4dc5acbf65bb
Revises: 6c6ec7e32f1b
Create Date: 2025-09-01 22:22:47.576879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc5acbf65bb'
down_revision = '6c6ec7e32f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
