"""update qr code ticket table

Revision ID: 63d162d3e78f
Revises: 71772ec5ab73
Create Date: 2025-09-16 23:15:29.324255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d162d3e78f'
down_revision = '71772ec5ab73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_data', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('issued_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ticket_qr_data'), ['qr_data'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_qr_data'))
        batch_op.drop_column('issued_at')
        batch_op.drop_column('qr_data')

    # ### end Alembic commands ###
