"""Add created_at to Order model

Revision ID: 71772ec5ab73
Revises: 4dc5acbf65bb
Create Date: 2025-09-16 01:05:17.739706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71772ec5ab73'
down_revision = '4dc5acbf65bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
