"""initial schema

Revision ID: f8229acb2825
Revises: 
Create Date: 2025-08-31 19:35:22.240167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8229acb2825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('use_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_role',
               existing_type=mysql.ENUM('USER', 'ORGANIZER', 'ADMIN'),
               nullable=False)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('phone'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('user_role',
               existing_type=mysql.ENUM('USER', 'ORGANIZER', 'ADMIN'),
               nullable=True)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('use_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transaction_id'))

    # ### end Alembic commands ###
