name: EasyTicket Feature CICD

on:
  push:
    branches:
      - feature/cicd

env:
  IMAGE_NAME: nguyentuong/easyticket

jobs:
  build-test-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: feature/cicd

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r easyticket/requirements.txt

      # 4. Run tests
      - name: Run Unit Tests
        run: |
          python -m unittest discover -s easyticket/app/tests

      # 5. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.run_number }} easyticket
          docker tag $IMAGE_NAME:${{ github.run_number }} $IMAGE_NAME:latest

      # 6. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 7. Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.run_number }}
          docker push $IMAGE_NAME:latest

      # 8. Trigger Render Deploy (placeholder)
      - name: Trigger Render Deploy
        run: |
          echo "Trigger Render deploy here..."
          # curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
